version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dentpaycra
    image: diorcokorea/dentpaycra
    volumes:
      - ./src:/app/src
      - /app/node_modules
    ports:
      - "8082:80"

# version: "3.8"

# services:
#   app:
#     container_name: dentpaypal
#     image: diorcokorea/dentpaypal
#     build:
#       context: .
#       dockerfile: Dockerfile
#     volumes:
#       - ./src:/app/src
#     ports:
#       - "8082 :8082"